from aiogram.types import KeyboardButton

menu = KeyboardButton("Меню")
support = KeyboardButton("Поддержка")
way_1 = KeyboardButton("Способ 1")
way_2 = KeyboardButton("Способ 2")
more = KeyboardButton("Подробнее")
back2menu = KeyboardButton("⬅ Меню")
cancel = KeyboardButton("/cancel")
cancel_2 = KeyboardButton("Отмена")
to_step_1 = KeyboardButton("К шагу 1")
to_step_2 = KeyboardButton("К шагу 2")
to_step_3 = KeyboardButton("К шагу 3")
to_step_4 = KeyboardButton("К шагу 4")
rules = KeyboardButton("Правила оформления")
commands = KeyboardButton("Команды")
button_cmd = KeyboardButton("Команда «Кнопка»")
wait_cmd = KeyboardButton("Команда «Задержка»")
switch_cmd = KeyboardButton("Команда «Переключатель»")
example_cmd = KeyboardButton("Пример")
scopes = KeyboardButton("Ограничения")
loading_script = KeyboardButton("Загрузка сценария")
loading_firmware = KeyboardButton("Загрузка прошивки")
loading_script_2 = KeyboardButton("Загрузить cценарий")